name: Feature Build and Test

on:
  push:
    branches:
      - feature/*

jobs:
  build_e_teste:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Instalando dependências
        run: yarn install

      - name: Build e testes
        run: |
          yarn build
          yarn test
